### ISSUE TITLE
Feature request: add command "all"

### ISSUE THREAD

**Issue by skarkkai** [AnilRedshift/captions_please_go#2]
As a visually impaired user I may not know if an image contains only text, only photo, or both. I suggest adding command "all", which would return all available information in order: alt text, image description, OCR.

**Comment by AnilRedshift** [comment]
This is done! I just need to push up a new version ( which I'll do soon) Thanks for the suggestion

**Comment by skarkkai** [comment]
I just tested this, but the bot said it didn't understand the command.
